In [ ]:
import numpy as np
arr1=np.array([1,2,3,4])
arr1b=np.array([9,8,7,6])
print(arr1)
print(np.shape(arr1))
print(arr1.dtype)

[1 2 3 4]
(4,)
int32


In [24]:
arr2=np.array([[1,2,3,4,5],[9,8,7,6,5]])
print(arr2)
print(np.shape(arr2))

[[1 2 3 4 5]
 [9 8 7 6 5]]
(2, 5)


In [25]:
arr3=np.array([[[11,22,33],[44,55,66]],[[99,88,77],[14,15,16]]])
print(arr3)
print(np.shape(arr3))

[[[11 22 33]
  [44 55 66]]

 [[99 88 77]
  [14 15 16]]]
(2, 2, 3)


In [18]:

arr5=np.ones((2,3))
print(arr5)

[[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
arr5=np.zeros((2,3))
print(arr5)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#creating an array of numbers 1 to 10 with difference 4
a = np.arange(1,10,4)
print(a)

[1 5 9]
