In [1]:
import numpy as np

In [2]:
print("version", np.__version__)

version 2.2.4


In [3]:
# 1d array 
a=np.array([1,2,3,4,5])
print("1D array: ",a)

1D array:  [1 2 3 4 5]


In [4]:
# 2D ARRAY
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
# 3D Array 
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
zero=np.zeros((2,2))
print(zero)

[[0. 0.]
 [0. 0.]]


In [9]:
one=np.ones((5,5))
print(one)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
import numpy as np
full_arr=np.full((4,3),6)
print(full_arr)

[[8 8 8]
 [8 8 8]
 [8 8 8]
 [8 8 8]]


In [14]:
i=np.eye(4)
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
range_arr=np.arange(0,5,2)
print(range_arr)

[0 2 4]


In [19]:
line=np.linspace(1,100,5)
print(line)

[  1.    25.75  50.5   75.25 100.  ]


In [20]:
rand_arr=np.random.rand(2,3)
print(rand_arr)

[[0.97521336 0.7010626  0.71035691]
 [0.43105504 0.14140859 0.7723247 ]]


In [21]:
randiant_arr=np.random.randint(1,100,size=(2,5))
print(randiant_arr)

[[21 21 90 26 42]
 [35 76 37 88  4]]


In [24]:
s=np.array([[1,2,3],[4,5,6]])
print(s)
print('Shape: ',s.shape)

[[1 2 3]
 [4 5 6]]
Shape:  (2, 3)


In [25]:
print('dimensions :',s.shape)

dimensions : (2, 3)


In [27]:
a=s.astype('float32')


In [29]:
print(a.dtype)

float32


In [33]:
c=s.reshape((3,2))
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [34]:
d=c.flatten()
print(d)

[1 2 3 4 5 6]


In [36]:
t=c.transpose()
print(t)

[[1 3 5]
 [2 4 6]]


In [40]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
join=np.concatenate((a,b))
print(join)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [41]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [42]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [45]:
un=np.array([5,3,9,1,-1])
sor=np.sort(un)
print(sor)

[-1  1  3  5  9]


In [49]:
array2=np.array([[1,2,3],[4,5,6]])
shape=array2.reshape(((3,2)))
print(shape)


[[1 2]
 [3 4]
 [5 6]]


In [50]:
x = np.array([10, 20, 30, 40])
y = np.array([1, 2, 3, 4])

print("Addition:", x + y)
print("Subtraction:", x - y)
print("Multiplication:", x * y)
print("Division:", x / y)
print("Power:", x ** 2)

Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Power: [ 100  400  900 1600]


In [51]:
data = np.array([4, 8, 15, 16, 23, 42])

print("Sum:", np.sum(data))
print("Mean:", np.mean(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
print("Standard deviation:", np.std(data))
print("Variance:", np.var(data))

Sum: 108
Mean: 18.0
Minimum: 4
Maximum: 42
Standard deviation: 12.315302134607444
Variance: 151.66666666666666


In [52]:
nums = np.array([1, 4, 9, 16])

print("Square root:", np.sqrt(nums))
print("Exponential:", np.exp(nums))
print("Natural log:", np.log(nums))
print("Sine:", np.sin(nums))

Square root: [1. 2. 3. 4.]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
Natural log: [0.         1.38629436 2.19722458 2.77258872]
Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332]


In [53]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

print("Element-wise multiplication:\n", m1 * m2)
print("Matrix multiplication (dot):\n", np.dot(m1, m2))
print("Matrix multiplication (matmul):\n", np.matmul(m1, m2))


Element-wise multiplication:
 [[ 5 12]
 [21 32]]
Matrix multiplication (dot):
 [[19 22]
 [43 50]]
Matrix multiplication (matmul):
 [[19 22]
 [43 50]]


In [54]:
e=np.array([1,2,3,4,5])
f=np.array([6,7,8,9,10])
print("sum: ",e+f)
print("Product: ",e*f)
print("Mean: ",e.mean())


sum:  [ 7  9 11 13 15]
Product:  [ 6 14 24 36 50]
Mean:  3.0


In [55]:
arr = np.array([10, 20, 30, 40, 50, 60])

print("Full array:", arr)
print("First element:", arr[0])
print("Last element:", arr[-1])
print("Elements from index 1 to 3:", arr[1:4])
print("Every second element:", arr[::2])
print("Reversed array:", arr[::-1])

Full array: [10 20 30 40 50 60]
First element: 10
Last element: 60
Elements from index 1 to 3: [20 30 40]
Every second element: [10 30 50]
Reversed array: [60 50 40 30 20 10]


In [57]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[0,1])

2


In [60]:
matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

print("Matrix:\n", matrix)
print("Element at row 1, col 2:", matrix[1, 2])
print("First row:", matrix[0, :])
print("First column:", matrix[:, 0])
print("Sub-matrix (rows 0-1, cols 1-2):\n", matrix[0:2, 1:3])

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, col 2: 6
First row: [1 2 3]
First column: [1 4 7]
Sub-matrix (rows 0-1, cols 1-2):
 [[2 3]
 [5 6]]
